-keep public class * extends android.app.Activity
-keep public class * extends android.app.Application
-keep public class * extends androidx.compose.runtime.**
-keepattributes *Annotation*
-dontwarn org.bouncycastle.jsse.**
-dontwarn org.conscrypt.*
-dontwarn org.openjsse.**
